### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by alphatroya**

### CODE REVIEW

**Comment by alphatroya** [comment]
The failed check was caused by old Swift syntax in the Example project. I think it will be solved when #12 will be closed

**Comment by mogol** [comment]
@alphatroya thanks for adding Carthage 
I will merge it after #12

**Comment by mogol** [comment]
I have updated project to Swif4 and replaced SwiftWebSocket with Starscream. Could you pls update pr? Is it possible to add CI step to check that Carthage integration is not broken?

**Comment by alphatroya** [comment]
I've update project for using Starscream framework. For check the carthage integration, I think `carthage build --no-skip-current` command will be enough.

**Comment by mogol** [comment]
👍 thanks!

**Pull request merged**
